"""add sms table

Revision ID: c552b9438b12
Revises: 80ef7244ed47
Create Date: 2022-12-26 11:33:53.882956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c552b9438b12'
down_revision = '80ef7244ed47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
