"""add phone column to sms

Revision ID: d27b82b9073f
Revises: e13127660525
Create Date: 2022-12-26 14:16:54.340826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27b82b9073f'
down_revision = 'e13127660525'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms', sa.Column('phone', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms', 'phone')
    # ### end Alembic commands ###
