"""add phone_verified column to user table

Revision ID: d951fda74f1f
Revises: c552b9438b12
Create Date: 2022-12-26 13:02:29.296330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd951fda74f1f'
down_revision = '80ef7244ed47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_verified')
    # ### end Alembic commands ###
