"""create sms table

Revision ID: e13127660525
Revises: d951fda74f1f
Create Date: 2022-12-26 13:58:54.913892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e13127660525'
down_revision = 'd951fda74f1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms',
    sa.Column('sms_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('auth_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sms_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms')
    # ### end Alembic commands ###
