version: "3.8"

services:
  api:
      image: login_api:latest
      ports:
        - "8000:8000"
      command: uvicorn --reload --host 0.0.0.0 --port 8000 app.main:app
      volumes:
        - .:/workspace:z
      depends_on:
        - db
      environment:
        DATABASE_URL: "postgresql://postgres:mypassword@db/user_db"
        JWT_SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"

  db:
    image: postgres:13
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "user_db"